name: prev_ler
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: "flutter"

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  intl: ^0.17.0
  form_validator: ^1.0.4
  flutter_riverpod: ^2.1.1
  fluttertoast: ^8.2.1
  flutter_secure_storage: ^8.0.0
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.6
  jwt_decoder: ^2.0.1
  flutter_staggered_grid_view: ^0.6.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2

flutter:
  assets:
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  uses-material-design: true
